### ISSUE TITLE
error: after runing  ./script/eval_mupots.sh 

### ISSUE THREAD

**Issue by daixiangzi** [dluvizon/scene-aware-3d-multi-human#3]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/24811131/221399750-964c3c86-f5a0-4a58-98cb-852d972afad7.png">

**Comment by daixiangzi** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/24811131/221399818-e40df25c-85e4-412c-a02e-43353997af4c.png">

**Comment by daixiangzi** [comment]
I replace input path with "--input_path=./output/mupots-Test/" in script, but error:FileNotFoundError: [Errno 2] No such file or directory: './output/mupots-Test/TS1/images/annot.mat';I doubt that I should place output fold content  to move  data/mupots-3d-eval/TS1/?

**Comment by daixiangzi** [comment]
I modify eval_mupots.py is ok, get some result about TS1:
| | TS1 | Avg. |
| :--: | :--: | :--: |
| mm_abs_error | 270.80 | 270.80 |
| mm_rel_error | 93.86 | 93.86 |
| mm_mrpe | 281.00 | 281.00 |
| pck_rel | 87.13 | 87.13 |
| ap25_root | 39.78 | 39.78 |
| abs_jitter | 11.78 | 11.78 |
| mm_abs_error_univ | 277.35 | 277.35 |
| mm_rel_error_univ | 82.04 | 82.04 |
| mm_mrpe_univ | 281.50 | 281.50 |
| pck_rel_univ | 91.20 | 91.20 |
| ap25_root_univ | 38.44 | 38.44 |
| abs_jitter_univ | 11.06 | 11.06 |

**Comment by dluvizon** [comment]
Hi @daixiangzi , thanks for reporting!
Could you please also point out what you have to change in ` eval_mupots.py ` ?

**Comment by daixiangzi** [comment]
I only modify follow two line:
`num_instances=num_instances[:1]  
  for ts_id in range(1, 2):` because I only test TS1
