### ISSUE TITLE
There is no run_instance_segmentation.py in the Mask2Former 

### ISSUE THREAD

**Issue by Seeseallllll** [dluvizon/scene-aware-3d-multi-human#9]
Thank you for your work!
When I try to run the ./script/preproc_data.sh ${path_to_video}
I find that There is no run_instance_segmentation.py in the Mask2Former (https://github.com/facebookresearch/Mask2Former).
preproc_data.sh：
"conda activate mask2former
pushd ./tools/Mask2Former
python run_instance_segmentation.py \"
Where can I find "run_instance_segmentation.py" or what command to replace this command with?

**Comment by dluvizon** [comment]
Hi @Seeseallllll ,
Thank you for your interest in our work.
Did you check the instructions about [external tools](https://github.com/dluvizon/scene-aware-3d-multi-human/blob/main/doc/external_tools.md#4-instance-segmentation) ?
You have to first update the submodule of Mask2Former, then apply a patch that will copy this script that you missed.

Please let me know if you still have problems after this.

**Comment by Seeseallllll** [comment]
Thanks for your reply!
I realized that I forgot to apply the patch file earlier.
I get it after "git apply  ../patches/mask2former_16c3bee.patch".
